Revert "cros: Scroll events anywhere on AppListView"
This reverts commit b3904d69169b6254bded130c1da4035ac338482e [formerly ad748185bcbd736a6ea3c263c1895e6d0dc31055].

Reason for revert: breaks compile:
../../ui/app_list/views/app_list_view.cc:1070:7: error: use of undeclared identifier 'Dismiss'
      Dismiss();


Original change's description:
> cros: Scroll events anywhere on AppListView
> 
> can change app grid pages
> 
> New behavior: Scroll events (ET_MOUSEWHEEL and ET_SCROLL) used to modify
> the app grid if the mouse was over the grid, and modify the AppListState
> otherwise.
> 
> Now, we want scroll events to first try to move the grid. If this
> succeds, set a timer to keep the stream of scrolling events from also
> closing the AppListView.
> 
> If the scroll could not move the grid, allow it to modify the
> AppListState.
> 
> I used a timer because there is no reliable way to both determine the
> end of an ET_SCROLL and the end of a mousewheel scroll. We need to avoid
> acting twice with one user intent to scroll one surface. The behavior of
> this change was reviewed by UX/PM and approved for M61.
> 
> Misc refactoring:
> - No longer need OnMouseWheel/OnScroll in AppsGridView because AppListView
>   will handle all scroll events.
> - Broke AppListView::HandleScroll into a few different functions because
>   it was starting to do multiple things.
> - In HandleScroll, also combined mousewheel and touchpad logic to avoid
>   code duplication.
> - Added tests to AppsGridView while debugging. Also moved the scroll test
>   from FullscreenAppListPresenterDelegateTest to
>   AppListViewFullscreenTest.
> 
> TEST=manual and automated
> TBR=newcomer@chromium.org
> 
> (cherry picked from commit 5a179200c757feb89eb0aeb1846fb6f775da904a [formerly 07e06ef4282818ffab806565c0fc05bfc1a5892e])
> 
> BUG: 769356
> Bug: 
> Change-Id: I15396b9845404d0c13de916e01ef62ea9af22ae8
> Reviewed-on: https://chromium-review.googlesource.com/688637
> Commit-Queue: Alex Newcomer <newcomer@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Yury Khmel <khmel@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#505112}
> Reviewed-on: https://chromium-review.googlesource.com/692995
> Reviewed-by: Alex Newcomer <newcomer@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3202@{#510}
> Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}

TBR=xiyuan@chromium.org,khmel@chromium.org,newcomer@chromium.org

Change-Id: I1bdc6f5886aa5af81d341a8caa7635847e841139
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/692751
Reviewed-by: Vladislav Kaznacheev <kaznacheev@chromium.org>
Cr-Commit-Position: refs/branch-heads/3202@{#513}
Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}
Former-commit-id: 012f938904d61b835bef148cd889461255e4c73b