Revert "Do not push the reseted needs_show_scrollbars to active tree"
This reverts commit 0f0d20fa3ab42e3b8cfa01477143a1cf7eac8fbb [formerly 85997065863790a2aa8aa1773d6ca7ea6a6a81fd].

Breaks official Android build

https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm/builds/8779

../../cc/layers/scrollbar_layer_unittest.cc: In member function 'virtual void cc::{anonymous}::AuraScrollbarLayerTest_ScrollbarLayerCreateAfterSetScrollable_Test::TestBody()':
../../cc/layers/scrollbar_layer_unittest.cc:829:17: error: 'class cc::Layer' has no member named 'SetScrollable'
   scroll_layer->SetScrollable(layer_tree_root->bounds());

BUG=740795

Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel
Change-Id: Id2d4b862593e4e69bc1e27e349a0670b677178f7
Reviewed-on: https://chromium-review.googlesource.com/576528
Reviewed-by: Alex Mineer <amineer@chromium.org>
Cr-Commit-Position: refs/branch-heads/3112@{#646}
Cr-Branched-From: 07faed0551ea9474531c25080552dfc7bccfa9e8 [formerly b6460e24cf59f429d69de255538d0fc7a425ccf9]-refs/heads/master@{#474897}
Former-commit-id: 08bc211aa6e21098474f43cd20c9c0b060e99b39