Revert "[Merge to M60] Show pointer (not I-beam) when mouse drags in the air"
This reverts commit 14529f0b3054fc42784f718807dc5c8177b8894d [formerly e0e2b3e5681e73642b7ab69026ec888b0b22e104].

Reason for revert: Breaking official Android builds

../../third_party/WebKit/Source/web/tests/LinkSelectionTest.cpp: In member function 'virtual void blink::LinkSelectionTest_DragOnNothingShowsPointer_Test::TestBody()':
../../third_party/WebKit/Source/web/tests/LinkSelectionTest.cpp:193:59: error: cannot convert 'base::TimeDelta' to 'double' for argument '1' to 'void blink::testing::RunDelayedTasks(double)'
   testing::RunDelayedTasks(TimeDelta::FromMilliseconds(50));

BUG=735852

Original change's description:
> [Merge to M60] Show pointer (not I-beam) when mouse drags in the air
> 
> This is a manual merge of:
> 
> A bug surfaced when Blink started to allow hidden selections.
> The condition "show I-beam if we have a non-empty selection"
> became too generous.
> 
> We should show an I-beam when:
> - Node is editable
> - Node is selectable
> - A link's text is being selected
> 
> Besides fixing the condition I moved its block into
> ShouldShowIBeamForNode() to try to gather stray I-beam
> logic into one place.
> 
> TEST=LinkSelectionTest.DragOnNothingShowsPointer
> 
> BUG=735852
> 
> (cherry picked from commit f7aec86a4de11eea665bac846acba91473f3a61b [formerly 0fd45cda7fa9de64706b81ecc97354df7769eac3])
> 
> Change-Id: I5366462c713155754de39b0c5d11fa33656eb6e3
> Reviewed-on: https://chromium-review.googlesource.com/566798
> Reviewed-by: Yoshifumi Inoue <yosin@chromium.org>
> Reviewed-by: David Bokan <bokan@chromium.org>
> Commit-Queue: Hugo Holgersson <hugoh@opera.com>
> Cr-Original-Commit-Position: refs/heads/master@{#486308}
> Reviewed-on: https://chromium-review.googlesource.com/572904
> Reviewed-by: Hugo Holgersson <hugoh@opera.com>
> Cr-Commit-Position: refs/branch-heads/3112@{#629}
> Cr-Branched-From: 07faed0551ea9474531c25080552dfc7bccfa9e8 [formerly b6460e24cf59f429d69de255538d0fc7a425ccf9]-refs/heads/master@{#474897}

TBR=yosin@chromium.org,bokan@chromium.org,hugoh@opera.com

Change-Id: Ic049226ef53be66fcbb2346a975a6457342c3bf2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 735852
Reviewed-on: https://chromium-review.googlesource.com/576830
Reviewed-by: Alex Mineer <amineer@chromium.org>
Cr-Commit-Position: refs/branch-heads/3112@{#648}
Cr-Branched-From: 07faed0551ea9474531c25080552dfc7bccfa9e8 [formerly b6460e24cf59f429d69de255538d0fc7a425ccf9]-refs/heads/master@{#474897}
Former-commit-id: 0edb193e1e3dd39f140353971e308023dc57a705