Revert of Use std::unique_ptr. (patchset #8 id:130001 of https://codereview.chromium.org/1780933003/ )
Reason for revert:
Another Android ambiguity due to implicit bool...

frameworks/base/core/jni/android/graphics/Utils.cpp:110:35: error: call of overloaded 'SkMemoryStream(SkAutoTUnref<SkData>&)' is ambiguous
     return new SkMemoryStream(data);

Original issue's description:
> Use std::unique_ptr.
>
> TBR=reed@google.com
>
> Committed: https://skia.googlesource.com/skia/+/10d848fb4c617af948faebbf0f7af2673a7c5a9e [formerly 20c1e3abfc681771f73eb19fde7284196e028940]
>
> Committed: https://skia.googlesource.com/skia/+/927b0146c08daa37442b9df654df22263975e5c7 [formerly 3dd9ed37c24611af86f0fe374bd3698b63f09450]

TBR=bungeman@google.com,mtklein@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1785353002


Former-commit-id: 218c846ac0509f70d6da3eb3a439fa89b589f7b5