Revert of Exact Ganesh Gradients for Special Cases (patchset #8 id:140001 of https://codereview.chromium.org/2223203003/ )
Reason for revert:
Chrome iOS build break
https://build.chromium.org/p/tryserver.chromium.mac/builders/ios-device/builds/50777/steps/compile/logs/stdio
error: unused function 'close_to_one_half'

Original issue's description:
> Remove generalized gradient code
>
> BUG=skia:
> GOLD_TRYBOT_URL= https://gold.skia.org/search?issue=2223203003
>
> Committed: https://skia.googlesource.com/skia/+/c80021433a9348fb4073ff3dbd06120edae8387d [formerly 0c63006b88a16e3418d92852a62771615799839d]
> Committed: https://skia.googlesource.com/skia/+/2addb6732f72254510a4253dfe3f738fc706739c [formerly 99818d69372d29a139935cfe5c379e491432931b]

TBR=bsalomon@google.com,fmenozzi@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=skia:

Review-Url: https://codereview.chromium.org/2241483003

Former-commit-id: cf736d7b66d76917c3384c0ad2f4cdc6d52db2a1