Add missing sk_tool_utils flags_common dependency
Not sure why this is only a problem on my workstation, but SampleApp linking is borked with

obj/gyp/../tools/sk_tool_utils.sk_tool_utils.o: In function `sk_tool_utils::platform_os_name()':
/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:128: undefined reference to `FLAGS_key'
/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:129: undefined reference to `FLAGS_key'
/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:127: undefined reference to `FLAGS_key'
obj/gyp/../tools/sk_tool_utils.sk_tool_utils.o: In function `sk_tool_utils::major_platform_os_name()':
/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:140: undefined reference to `FLAGS_key'
/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:141: undefined reference to `FLAGS_key'
obj/gyp/../tools/sk_tool_utils.sk_tool_utils.o:/mnt/screamin/src/blink/src/third_party/skia/out/Debug/../../tools/sk_tool_utils.cpp:139: more undefined references to `FLAGS_key' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

R=mtklein@google.com
GOLD_TRYBOT_URL= https://gold.skia.org/search?issue=2464903002

Review-Url: https://codereview.chromium.org/2464903002

Former-commit-id: fb4b9a27a1a0267e44aa4c8766322e53a06d3c37