Revert "remove legacy fontmgr flag from flutter"
This reverts commit 4958c89640c187ee91cc7bdd3081e7a234878b79 [formerly 7077ae855519a23b087ded7386e18b475ac73c48].

Reason for revert: Breaking flutter [1]:

../../flutter/sky/engine/platform/fonts/fuchsia/FontCacheFuchsia.cpp:136:53: error: no member named 'createFromData' in 'SkFontMgr'
  return sk_sp<SkTypeface>(SkFontMgr::RefDefault()->createFromData(data.get()));
                           ~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.

[1] https://luci-logdog.appspot.com/v/?s=fuchsia%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8966486899186212448%2F%2B%2Fsteps%2Fbuild_fuchsia%2F0%2Fsteps%2Fninja%2F0%2Fstdout

Original change's description:
> remove legacy fontmgr flag from flutter
> 
> Bug: skia:
> Change-Id: I82d16b398ea8bb7309378f475d94d9dea0b263d5
> Reviewed-on: https://skia-review.googlesource.com/56160
> Reviewed-by: Mike Reed <reed@google.com>
> Commit-Queue: Mike Reed <reed@google.com>

TBR=reed@google.com,reed@chromium.org

Change-Id: I942a9c51dd4673fb2088610ddc2bffd414fbc4d8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia:
Reviewed-on: https://skia-review.googlesource.com/56320
Reviewed-by: Leon Scroggins <scroggo@google.com>
Commit-Queue: Leon Scroggins <scroggo@google.com>

Former-commit-id: da6cf4e97ca334b408dda2344b6758970802eddd