Revert "Error message for voice interaciton shortcut on secondary user"
This reverts commit 1a53df01c2f40abffef3981255f4c1a04d31c9f8 [formerly 45031fef50608beca3ef427352076558e102be75].

Reason for revert: breaks compile ash/accelerators/accelerator_controller.cc:609:43: error: no member named 'GetPrimaryUserSession' in 'ash::SessionController'

Original change's description:
> Error message for voice interaciton shortcut on secondary user
> 
> Show a toast with error message when voice interaction shortcut is
> hitted on secondary user.
> 
> BUG=b/64692521
> TBR=updowndota@chromium.org
> 
> (cherry picked from commit 81ab106ffa0f24ba8260838d318c27eeb3714d54 [formerly a2ba28955b5bcf7a539d40f66cf3c5198db88566])
> 
> Change-Id: I2a879c868a0d1b476b74a055f1eb1e1d6adf2b22
> Reviewed-on: https://chromium-review.googlesource.com/634628
> Commit-Queue: Yue Li <updowndota@chromium.org>
> Reviewed-by: Mitsuru Oshima <oshima@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#497556}
> Reviewed-on: https://chromium-review.googlesource.com/639395
> Reviewed-by: Vladislav Kaznacheev <kaznacheev@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3163@{#950}
> Cr-Branched-From: e88a7fd797602ff08086e1663443abb227a71a68 [formerly ff259bab28b35d242e10186cd63af7ed404fae0d]-refs/heads/master@{#488528}

TBR=kaznacheev@chromium.org,oshima@chromium.org,updowndota@chromium.org

Change-Id: I668db51c12295e6e0296954e7e02e11fde5e44f0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b/64692521
Reviewed-on: https://chromium-review.googlesource.com/639165
Reviewed-by: Vladislav Kaznacheev <kaznacheev@chromium.org>
Cr-Commit-Position: refs/branch-heads/3163@{#953}
Cr-Branched-From: e88a7fd797602ff08086e1663443abb227a71a68 [formerly ff259bab28b35d242e10186cd63af7ed404fae0d]-refs/heads/master@{#488528}
Former-commit-id: a94d707723ee88d57c517955a0c25c5ba7f6df98