Revert "Fix crash in content::BrowserPlugin::Destroy"
This reverts commit 6f3916992b3f4f89fe225be3174b28e204c674e9 [formerly ac09cad83949fe402d89dabed10eaa4d01202950].

Reason for revert: Compilation error
../../content/renderer/render_widget.cc(2634,37):  error: use of undeclared identifier 'GetOriginalScreenInfo'
  browser_plugin->ScreenInfoChanged(GetOriginalScreenInfo());

Original change's description:
> Fix crash in content::BrowserPlugin::Destroy
> 
> We thought embedding_render_widget_ would outlive the BrowserPlugin, but
> apparently not, so use weak pointers to ensure we don't access
> embedding_render_widget_ once it's gone.
> 
> TBR=samans@chromium.org
> 
> (cherry picked from commit 86f8c5132c0f22b79707487cfd19b305950f6245 [formerly 50d1e0c194362ba62889fb635a4241160da4e239])
> 
> Bug: 812966
> Change-Id: I7f374a63bd34db3cb616fa961d7c504570c5ef2d
> Reviewed-on: https://chromium-review.googlesource.com/959239
> Reviewed-by: Antoine Labour <piman@chromium.org>
> Commit-Queue: Saman Sami <samans@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#542890}
> Reviewed-on: https://chromium-review.googlesource.com/969327
> Reviewed-by: Saman Sami <samans@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3359@{#316}
> Cr-Branched-From: 0d720befa68dd312f58d12edcf8c90bd2cf17d54 [formerly 66afc5e5d10127546cc4b98b9117aff588b5e66b]-refs/heads/master@{#540276}

TBR=piman@chromium.org,samans@chromium.org

Change-Id: I0e1c70227cbe01a0a8ac5dfe81b9d5da9760ae8f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 812966
Reviewed-on: https://chromium-review.googlesource.com/969227
Reviewed-by: Saman Sami <samans@chromium.org>
Cr-Commit-Position: refs/branch-heads/3359@{#327}
Cr-Branched-From: 0d720befa68dd312f58d12edcf8c90bd2cf17d54 [formerly 66afc5e5d10127546cc4b98b9117aff588b5e66b]-refs/heads/master@{#540276}
Former-commit-id: 052e45c6ff3a3411a825d09091cb1f2a35adf85a