Revert "Make TessellatingPathOp be a non-legacy GrMeshDrawOp"
This reverts commit 643794e393acb1d43c61158e401245cb2dd51c85 [formerly 086ce11386849c445a99c7bb8c43947f54618a75].

Reason for revert: Looks to be upsetting the bots (grglgpu.cpp(2766): fatal error: "assert(!useHWAA || rt->isStencilBufferMultisampled())")

Original change's description:
> Make TessellatingPathOp be a non-legacy GrMeshDrawOp
> 
> Change-Id: Ic92fdca7bdca91eab3a87e4fea3972ffdcfd5b12
> Reviewed-on: https://skia-review.googlesource.com/21867
> Reviewed-by: Jim Van Verth <jvanverth@google.com>
> Commit-Queue: Brian Salomon <bsalomon@google.com>

TBR=jvanverth@google.com,bsalomon@google.com

Change-Id: Ibb0c8f8f4e2dea018b54686ab780535e2f69539a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://skia-review.googlesource.com/22060
Reviewed-by: Ethan Nicholas <ethannicholas@google.com>
Commit-Queue: Ethan Nicholas <ethannicholas@google.com>

Former-commit-id: 7343c197fc91c6cedc019dd5fed69969a5d317ca