Revert "[Payment Request] Records metrics when request is aborted or page goes away"
This reverts commit b07cc34a99fd965383f587fc771ab7c364b59486 [formerly 81962dd0b997caed055fa5589c52f724aff342d2].

Reason for revert: this CL depends on https://chromium-review.googlesource.com/c/chromium/src/+/646660 that has not been cherry-picked in branch 3202 thus breaking the build with the following error:

../../ios/chrome/browser/ui/payments/payment_request_manager.mm:1078:23: error: no member named 'IsRendererInitiated' in 'web::NavigationContext'
          navigation->IsRendererInitiated()
          ~~~~~~~~~~  ^
1 error generated.

Original change's description:
> [Payment Request] Records metrics when request is aborted or page goes away
> 
> Refactors the abort logic and helper functions.
> Records the appropriate journey logger metrics when the request is aborted.
> Records the appropriate journey logger metrics when the page/tab goes away.
> Adds the remainder of the journey logger tests.
> 
> TBR=mahmadi@chromium.org
> 
> (cherry picked from commit fb92270a3ac90af73e498beb50fa31d484800350 [formerly 81b057f734465e321da2ba8221d29605a34cba75])
> 
> Bug: 761357, 602666
> Change-Id: I65a1196a530c2bded086e1edd94d915f3ff8acc8
> Reviewed-on: https://chromium-review.googlesource.com/646877
> Commit-Queue: mahmadi (Moe) <mahmadi@chromium.org>
> Reviewed-by: Marc-Antoine Courteau <macourteau@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#499287}
> Reviewed-on: https://chromium-review.googlesource.com/660400
> Reviewed-by: Moe Ahmadi <mahmadi@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3202@{#132}
> Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}

TBR=macourteau@chromium.org,mahmadi@chromium.org

Change-Id: Idca82702136652d17d07b2c315243a7c925db34e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 761357, 602666
Reviewed-on: https://chromium-review.googlesource.com/663540
Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
Cr-Commit-Position: refs/branch-heads/3202@{#168}
Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}
Former-commit-id: 0aa757d1ebc735a2533a8a77a11bd352f378a99e