Revert "Remove profile info cache entry on user removal on Chrome OS."
This reverts commit 423b713e0d1bc1313fe6e559d42586269b1e5b49 [formerly b228999b998658b6b91fa0399f08110fb69e9250].

Reason for revert: This broke build:
profile_info_cache.cc:758:26: error: no member named 'kUserNameKey' in 'ProfileAttributesEntry';

Original change's description:
> Remove profile info cache entry on user removal on Chrome OS.
> 
> Chrome OS removes users when profiles are not loaded, and Chrome does not know
> the exact profile path until it is mounted. So we need to be able to remove
> entries from ProfileInfoCache based solely on AccountId.
> 
> This Cl implements removal of cache entries given the AccountId and engages it
> on Chrome OS.
> 
> TBR=alemate@chromium.org
> 
> (cherry picked from commit 3d5e1096f1c3edb82740d5f0b9256033cbfe7b5e [formerly 4084f503be1913290db968dc81f6ceb9fe796fbc])
> 
> Bug: 808125
> Change-Id: I9f8e3a5f1004d119425b92a4bdc3d8011a526dd5
> Reviewed-on: https://chromium-review.googlesource.com/905751
> Reviewed-by: anthonyvd <anthonyvd@chromium.org>
> Reviewed-by: Bernhard Bauer <bauerb@chromium.org>
> Commit-Queue: Alexander Alekseev <alemate@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#537905}
> Reviewed-on: https://chromium-review.googlesource.com/938571
> Reviewed-by: Alexander Alekseev <alemate@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3325@{#603}
> Cr-Branched-From: 09f06fcf0fa239ed52c280c47686a4b3d4ed8f36 [formerly bc084a8b5afa3744a74927344e304c02ae54189f]-refs/heads/master@{#530369}

TBR=bauerb@chromium.org,alemate@chromium.org,anthonyvd@chromium.org

Change-Id: Iec63e9155c5b735259873a3109fa6bbf89a4f889
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 808125
Reviewed-on: https://chromium-review.googlesource.com/939241
Reviewed-by: Alexander Alekseev <alemate@chromium.org>
Cr-Commit-Position: refs/branch-heads/3325@{#604}
Cr-Branched-From: 09f06fcf0fa239ed52c280c47686a4b3d4ed8f36 [formerly bc084a8b5afa3744a74927344e304c02ae54189f]-refs/heads/master@{#530369}
Former-commit-id: 5737954dd4b2f08b1a5fac798c3fe412edc3c1ff