Revert "Revert "8-bit jumper on armv8""
This reverts commit 17a04df096556e47adb3f9128c310383a7de16ed [formerly 6d13575108299951ecdfba6d85c915fcec2bc028].

Now with guards for "errors" like this:
    external/skia/src/jumper/SkJumper_stages_8bit.cpp:240:50: error:
    'memcpy' called with size bigger than buffer
                case 12: memcpy(&v, src, 12*sizeof(T)); break;

This code is unreachable and generally removed by Clang's optimizer
anyway... as far as I can tell the code generation diff is arbitrary.

Change-Id: I6216567caaa6166f71258bd25343a09e93892a10
Reviewed-on: https://skia-review.googlesource.com/39961
Reviewed-by: Mike Klein <mtklein@chromium.org>
Commit-Queue: Mike Klein <mtklein@chromium.org>

Former-commit-id: 9d7e57d509149dd2fcb3ba73ea8f4cdce11f84bd