Revert of Fix double ripple on activated flood fill ripple (patchset #1 id:1 of https://codereview.chromium.org/2640383002/ )
Reason for revert:
Causes compile-time failure:

../../ui/views/animation/flood_fill_ink_drop_ripple.cc:335:46: error: no viable conversion from 'ui::LayerAnimationElement *' to 'std::unique_ptr<ui::LayerAnimationElement>'
 std::unique_ptr<ui::LayerAnimationElement> element =

Original issue's description:
> Fix double ripple on activated flood fill ripple
>
> When switching from pending to activated state, there is no need to do
> more animations as the final state of animations for these states are
> the same. Otherwise, janks on slow devices might create some unwanted
> effects like double ripples.
>
> BUG=670831
> TEST=manual
>
> Review-Url: https://codereview.chromium.org/2615613003
> Cr-Commit-Position: refs/heads/master@{#443366}
> (cherry picked from commit 9afa9d6e7d66d3df9b93ba760c7df42f301a71aa [formerly 30c4e21c362f23e2a40c5bba0483e59c3fc672ff])
>
> Review-Url: https://codereview.chromium.org/2640383002 .
> Cr-Commit-Position: refs/branch-heads/2924@{#801}
> Cr-Branched-From: 20dccad4a0c728c2e904bd3cea6523f4fb2eea0c [formerly 3a87aecc31cd1ffe751dd72c04e5a96a1fc8108a]-refs/heads/master@{#433059}
> Committed: https://chromium.googlesource.com/chromium/src/+/079ddc3e72a14a0a773b9ecfb839813384225de3 [formerly fce107cf1b0ff1ed005d256e72feb2737232c9d3]

TBR=
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=670831

Review-Url: https://codereview.chromium.org/2644943002
Cr-Commit-Position: refs/branch-heads/2924@{#802}
Cr-Branched-From: 20dccad4a0c728c2e904bd3cea6523f4fb2eea0c [formerly 3a87aecc31cd1ffe751dd72c04e5a96a1fc8108a]-refs/heads/master@{#433059}

Former-commit-id: 6ed6a13a45f4c06bd9121bda4a67b16b59079210