Revert "simplify api to bitmapcache"
This reverts commit bd9ce8e05cfa10a4fb67b65ab86f46785cc8404d [formerly 9f4b0ae91e1875831cc11f0629b5db998ad85438].

Reason for revert: Nanobench asserts.

../../../src/core/SkBitmapCache.cpp:81: fatal error: "assert(scaledWidth != image->width() || scaledHeight != image->height())"
Aborted
Command exited with code 134
step returned non-zero exit code: 134

https://chromium-swarm.appspot.com/task?id=351b1d10c7936310&refresh=10

Original change's description:
> simplify api to bitmapcache
> 
> Force all Find callers to make a bitmpacachedesc, which now
> has more rigid validation.
> 
> Goal is to ensure we never make two desc (which turn into keys)
> that look different but represent the same image/transformation.
> 
> BUG=skia:
> 
> Change-Id: I8571837ee4754a69acc99e949bee9a465fa25f2b
> Reviewed-on: https://skia-review.googlesource.com/10114
> Commit-Queue: Mike Reed <reed@google.com>
> Reviewed-by: Brian Osman <brianosman@google.com>
> 

TBR=brianosman@google.com,fmalita@chromium.org,reed@google.com,reviews@skia.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=skia:

Change-Id: I21b3c8a5bae409ba740cfc28b352c3b970dcf5af
Reviewed-on: https://skia-review.googlesource.com/10171
Reviewed-by: Florin Malita <fmalita@chromium.org>
Commit-Queue: Florin Malita <fmalita@chromium.org>

Former-commit-id: dd1b4e94c4298213f1f238a8634471086d6749fb