Revert of [M53 cherry-pick] Migrate ArcUserDataService into ArcAuthService. (patchset #1 id:1 of https://codereview.chromium.org/2248353002/ )
Reason for revert:
Compilation problem:

../../chrome/browser/chromeos/arc/arc_auth_service.cc:244:34: error: no member named 'stopped' in 'arc::ArcBridgeService'

Original issue's description:
> Migrate ArcUserDataService into ArcAuthService.
>
> There are race problems around data removing.
> One of the cause is that state management is done in
> ArcAuthService and ArcUserDataService separately.
>
> This CL migrates ArcUserDataService into ArcAuthService
> so that we can remove the data when necessary.
>
> BUG=633258, 636218
> TEST=Ran manually.
>      - "Enable -> ARC boot wait -> Disable" triggers data removal after
>        ARC stop.
>      - "Enable -> Disable before ARC boot" triggers immediate data
>        removal.
>      - "Enable -> ARC boot wait -> Kill ARC instance" does not trigger
>        data removal.
> R=dspaid@chromium.org, lhchavez@chromium.org
> TBR=khmel@chromium.org, lhchavez@chromium.org, stevenjb@chromium.org
>
> Review-Url: https://codereview.chromium.org/2209173002
> Cr-Commit-Position: refs/heads/master@{#411923}
> (cherry picked from commit 6a88d95e977b4c320fa5dfa48a462754a7b91fe2 [formerly 6d95ad318e992261c45f5a88a0a599663a6d66ae])
>
> Committed: https://chromium.googlesource.com/chromium/src/+/31165c975d9a538eeafb7a850f1c0e6be9b770ee [formerly d7ca35a59c7bd8c7ddd78d7682458e48e6b4e934]

TBR=dspaid@chromium.org,lhchavez@chromium.org,stevenjb@chromium.org,hidehiko@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=633258, 636218

Review-Url: https://codereview.chromium.org/2255673004
Cr-Commit-Position: refs/branch-heads/2785@{#671}
Cr-Branched-From: 1ac8cbeb262a801827381e10bb796676610ddf00 [formerly 68623971be0cfc492a2cb0427d7f478e7b214c24]-refs/heads/master@{#403382}

Former-commit-id: 30deef189906f95894267f177c151ca9e95c60f3