Revert "Delete more event tracing macros"
This reverts commit 3eafe29e8471a69f9a995a86f98a4a890cbfc588 [formerly fd52317bf6d2acdbedf7477093204c9d642fcc22].

Reason for revert: 

../../flutter/shell/common/skia_event_tracer_impl.cc:34:12: error: use of undeclared identifier 'TRACE_EVENT_PHASE_BEGIN'
      case TRACE_EVENT_PHASE_BEGIN:

:(


Original change's description:
> Delete more event tracing macros
> 
> Also tried to clean up the comments to be clearer.
> 
> Bug: skia:
> Change-Id: I9762564a7f59bbfbd6a43afe902596d25ff1d523
> Reviewed-on: https://skia-review.googlesource.com/25364
> Reviewed-by: Mike Klein <mtklein@chromium.org>
> Commit-Queue: Brian Osman <brianosman@google.com>

TBR=mtklein@chromium.org,brianosman@google.com

Change-Id: I3869991b8aa3d0d67d12fbe76a207a1167801a63
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia:
Reviewed-on: https://skia-review.googlesource.com/25440
Reviewed-by: Mike Klein <mtklein@google.com>
Commit-Queue: Mike Klein <mtklein@google.com>

Former-commit-id: d04598734d647786145fd2d58655be3d7a3c962b