Revert "[Home] Account for incognito in modern tab title"
This reverts commit 9fe8ac2bcf1b822ad75d905a39fc1b593d515190 [formerly 6dd103c99f5d0da25e410e1b23ce8a5dc29cd876].

Reason for revert: this broke
https://uberchromegw.corp.google.com/i/official.android/builders/official-arm/builds/2411
with error message:
../../chrome/android/java/src/org/chromium/chrome/browser/compositor/LayerTitleCache.java:128: error: cannot find symbol
        if (!DeviceFormFactor.isTablet() && !FeatureUtilities.isChromeHomeModernEnabled())

Original change's description:
> [Home] Account for incognito in modern tab title
> 
> Titles in Chrome Modern are not always white, incognito still uses a
> dark theme.
> 
> BUG=760740
> TBR=mdjones@chromium.org
> 
> (cherry picked from commit db2916167d2a24b704ca69cfd97c95fbba9bc4d9 [formerly fba6588489fd94a60be80552b0415548540bf936])
> 
> Change-Id: I82800234101f3755dcb3214c65942ae82e59b3d9
> Reviewed-on: https://chromium-review.googlesource.com/651570
> Reviewed-by: Theresa <twellington@chromium.org>
> Commit-Queue: Matthew Jones <mdjones@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#499781}
> Reviewed-on: https://chromium-review.googlesource.com/661319
> Reviewed-by: Matthew Jones <mdjones@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3202@{#147}
> Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}

TBR=twellington@chromium.org,mdjones@chromium.org

Change-Id: I12ab4b52aa3c9f6007f26388cfe14e40b3e90f90
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 764200,760740
Reviewed-on: https://chromium-review.googlesource.com/663381
Reviewed-by: John Mellor <johnme@chromium.org>
Cr-Commit-Position: refs/branch-heads/3202@{#162}
Cr-Branched-From: 3efa1198dfb9f65f00675896e8ea5a4db4f46842 [formerly fa6a5d87adff761bc16afc5498c3f5944c1daa68]-refs/heads/master@{#499098}
Former-commit-id: b0bb3a87fba58edbd3c19b2b6ad3e4a9e6fb8258