Merge 59: Wait for RequireBitstreamBuffers() after reset in VEAEncoder
This CL solves the issues resulting from mid-stream resize in VEAEncoder.
- RequireBitstreamBuffers() returns the updated |vea_requested_input_coded_size|,
so we should wait for it before copying any frame. Using the older value can result in
failed VideoFrame::WrapExternalSharedMemory() call.
- Check VideoFrame::WrapExternalSharedMemory() result before moving on in case
we end up with sizes that don't work.

BUG=714132
TEST= Tested the reported extension with resize.

Review-Url: https://codereview.chromium.org/2838453003
Cr-Commit-Position: refs/heads/master@{#467344}
(cherry picked from commit 1da081f8337ff7e62b754c2be700685cc7216796 [formerly d149aa5e140e8158e09a8b410660a8d72b4eec56])
NOTRY=true
NOPRESUBMIT=true
TBR=mcasas@chromium.org

Review-Url: https://codereview.chromium.org/2846783004
Cr-Commit-Position: refs/branch-heads/3071@{#274}
Cr-Branched-From: 91bcc2d22c7c7ff519c4f50384d9bdc5a08671e0 [formerly a106f0abbf69dad349d4aaf4bcc4f5d376dd2377]-refs/heads/master@{#464641}

Former-commit-id: 5157dc250abdaa7b45b35069dc356fe3d0d25102